# Generated by Django 5.0.14 on 2026-06-18 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=150)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=50)),
                ("gst_number", models.CharField(max_length=15)),
                ("state_code", models.CharField(default="24-GJ", max_length=10)),
                ("pan_number", models.CharField(max_length=10)),
                ("bank_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=30)),
                ("ifsc_code", models.CharField(max_length=20)),
                (
                    "terms_conditions",
                    models.TextField(
                        default="1) Goods Once Sold will not be taken back.\n2) Goods are delivered at owner's risk and insurance option.\n3) Please Check The RF Within 5 Days Otherwise We Are Not Responsible.\n4) Interest will be charged @ 24% p.a.\n5) Subject to SURAT Jurisdiction."
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Company Settings",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("address", models.TextField()),
                ("gst_number", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_number", models.CharField(max_length=50, unique=True)),
                ("challan_no", models.CharField(blank=True, max_length=100, null=True)),
                ("broker", models.CharField(blank=True, max_length=100, null=True)),
                ("hsn_code", models.CharField(blank=True, max_length=50, null=True)),
                ("bill_date", models.DateField()),
                (
                    "gross_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "blouse_charge",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "sgst_percent",
                    models.DecimalField(decimal_places=2, default=2.5, max_digits=5),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "cgst_percent",
                    models.DecimalField(decimal_places=2, default=2.5, max_digits=5),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "round_off",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("amount_in_words", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="billing.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_ch_no", models.CharField(blank=True, max_length=50, null=True)),
                ("lot_no", models.CharField(blank=True, max_length=50, null=True)),
                ("design", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "meter",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "t_qty",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "p_qty",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "s_qty",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "qty",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.invoice",
                    ),
                ),
            ],
        ),
    ]
