# Generated by Django 5.0.14 on 2026-06-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_company_plan_expiry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="bank_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="invoice",
            name="check_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="check_no",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="invoice",
            name="credited_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tds",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
    ]
