# Generated by Django 4.2.30 on 2026-06-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_remove_company_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
    ]
