# Generated by Django 4.2.30 on 2026-06-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_alter_customer_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="account_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="ifsc_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="state_code",
            field=models.CharField(
                blank=True, default="24-GJ", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="terms_conditions",
            field=models.TextField(
                blank=True,
                default="1) Goods Once Sold will not be taken back.\n2) Goods are delivered at owner's risk and insurance option.\n3) Please Check The RF Within 5 Days Otherwise We Are Not Responsible.\n4) Interest will be charged @ 24% p.a.\n5) Subject to SURAT Jurisdiction.",
                null=True,
            ),
        ),
    ]
