# Generated by Django 5.0.14 on 2026-07-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_alter_company_account_number_alter_company_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="grand_total",
            new_name="amount",
        ),
    ]
