# Generated by Django 5.0.14 on 2026-07-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0011_rename_grand_total_invoice_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="credited_amount",
        ),
        migrations.AddField(
            model_name="invoice",
            name="debit_credit_note",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
