# Generated by Django 5.0.14 on 2026-07-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0013_remove_invoice_debit_credit_note_invoice_note_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_challan",
            field=models.BooleanField(default=False),
        ),
    ]
