# Generated by Django 4.2.30 on 2026-07-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0016_remove_company_start_bill_no_company_bill_no_prefix_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="extra_charges",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoice",
            name="extra_charges_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="invoice",
            name="extra_charges_type",
            field=models.CharField(
                choices=[("add", "Add"), ("cut", "Cut")], default="add", max_length=10
            ),
        ),
    ]
