# Generated by Django 4.2.30 on 2026-07-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0018_alter_invoice_extra_charges_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="extra_charges_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
