# Generated by Django 4.2.30 on 2026-07-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0022_dashboarditem_lot_no_dashboarditem_p_ch_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboarditem",
            name="meter",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
