# Generated by Django 4.2.30 on 2026-07-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0023_dashboarditem_meter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboarditem",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Done", "Done")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
