# Generated by Django 5.0.14 on 2026-06-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="gst_number",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
    ]
