# Generated by Django 5.0.14 on 2026-06-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0003_invoice_customer_address_invoice_customer_gst_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="bill_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
