# Generated by Django 5.0.14 on 2026-06-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_invoice_bill_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="plan_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
