# Generated by Django 5.0.14 on 2026-06-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_migrate_to_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="company",
            name="gst_number",
        ),
        migrations.RemoveField(
            model_name="company",
            name="pan_number",
        ),
        migrations.RemoveField(
            model_name="company",
            name="plan_expiry_date",
        ),
    ]
