# Generated by Django 5.0.14 on 2026-07-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0012_remove_invoice_credited_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="debit_credit_note",
        ),
        migrations.AddField(
            model_name="invoice",
            name="note_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="note_type",
            field=models.CharField(
                blank=True,
                choices=[("credit", "Credit Note"), ("debit", "Debit Note")],
                default="",
                max_length=10,
            ),
        ),
    ]
