# Generated by Django 4.2.30 on 2026-07-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_invoice_is_challan"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="start_bill_no",
            field=models.CharField(blank=True, default="1", max_length=50, null=True),
        ),
    ]
