# Generated by Django 4.2.30 on 2026-07-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0015_company_start_bill_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="start_bill_no",
        ),
        migrations.AddField(
            model_name="company",
            name="bill_no_prefix",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="bill_no_start_number",
            field=models.IntegerField(default=1),
        ),
    ]
