# Generated by Django 4.2.30 on 2026-07-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0017_invoice_extra_charges_invoice_extra_charges_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="extra_charges",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="extra_charges_type",
            field=models.CharField(
                blank=True,
                choices=[("add", "Add"), ("cut", "Cut")],
                default="add",
                max_length=10,
            ),
        ),
    ]
