# Generated by Django 4.2.30 on 2026-07-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0019_alter_invoice_extra_charges_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=150)),
                ("date", models.DateField()),
                ("design", models.CharField(blank=True, default="", max_length=100)),
                (
                    "qty",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Paid", "Paid")],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
