# Generated by Django 4.2.30 on 2026-07-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0020_dashboarditem"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboarditem",
            name="billing_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dashboarditem",
            name="broker",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="dashboarditem",
            name="gst_number",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AddField(
            model_name="dashboarditem",
            name="hsn_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
