# Generated by Django 4.2.30 on 2026-07-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0021_dashboarditem_billing_address_dashboarditem_broker_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboarditem",
            name="lot_no",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="dashboarditem",
            name="p_ch_no",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
