# Generated by Django 4.2.30 on 2026-07-24 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0024_alter_dashboarditem_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="dashboard_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="billing.dashboarditem",
            ),
        ),
    ]
