# Generated by Django 4.2.30 on 2026-07-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0025_invoice_dashboard_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="default_hsn_code",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
