# Generated by Django 4.2.30 on 2026-07-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0026_company_default_hsn_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboarditem",
            name="products_json",
            field=models.TextField(blank=True, default="[]"),
        ),
    ]
