# Generated by Django 4.2.30 on 2026-09-16 18:00

from django.db import migrations, models


def populate_company_from_system_data(apps, schema_editor):
    Company = apps.get_model('billing', 'Company')
    company = Company.objects.first()
    if company:
        try:
            from billing.config_helper import load_config, parse_date
            config = load_config()
            if config.get('company_name'):
                company.company_name = config['company_name']
            if config.get('gst_number'):
                company.gst_number = config['gst_number']
            if config.get('pan_number'):
                company.pan_number = config['pan_number']
            if config.get('plan_expiry_date'):
                company.plan_expiry_date = parse_date(config['plan_expiry_date'])
            if config.get('license_key'):
                company.license_key = config['license_key']
            if config.get('user_id'):
                company.user_id = config['user_id']
            company.save()
        except Exception as e:
            print(f"Error populating company data in migration: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0027_dashboarditem_products_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="company",
            name="gst_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="company",
            name="license_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="pan_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="company",
            name="plan_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="user_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.RunPython(populate_company_from_system_data, reverse_code=migrations.RunPython.noop),
    ]
