# Generated by Django 4.2.30 on 2026-09-18 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def assign_existing_data_to_first_user(apps, schema_editor):
    try:
        from django.contrib.auth import get_user_model
        # Use apps.get_model for safe migration access
        User = apps.get_model('auth', 'User')
        first_user = User.objects.first()
        if not first_user:
            return
        
        Company = apps.get_model('billing', 'Company')
        Customer = apps.get_model('billing', 'Customer')
        Invoice = apps.get_model('billing', 'Invoice')
        DashboardItem = apps.get_model('billing', 'DashboardItem')
        
        Company.objects.filter(user__isnull=True).update(user=first_user)
        Customer.objects.filter(user__isnull=True).update(user=first_user)
        Invoice.objects.filter(user__isnull=True).update(user=first_user)
        DashboardItem.objects.filter(user__isnull=True).update(user=first_user)
    except Exception as e:
        print(f"Note on data assignment during migration: {e}")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0028_company_company_name_company_gst_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="user_id",
        ),
        migrations.AddField(
            model_name="company",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dashboarditem",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="bill_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("bill_number__isnull", False),
                    models.Q(("bill_number", ""), _negated=True),
                ),
                fields=("user", "bill_number"),
                name="unique_user_bill_number",
            ),
        ),
        migrations.RunPython(assign_existing_data_to_first_user, migrations.RunPython.noop),
    ]
